server:
  port: 10011
spring:
  application:
    name: eureka-server



eureka:
  instance:
    # Eureka 服务器的主机名
    hostname: 127.0.0.1
  client:
    # 不将自己注册到 Eureka 服务器
    register-with-eureka: false
    # 不从 Eureka 服务器获取服务注册信息
    fetch-registry: false
    service-url:
      # Eureka 服务器的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka