server:
  port: 8050

spring:
  application:
    name: fegin-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC #Asia/Shanghai
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 7001
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        port: 8081
        namespace: topsource_dev
        group: TOPSOURCE_GROUP
      config:
        import-check:
          enabled: false



